# Generated by Django 4.1.2 on 2022-10-25 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_likeunlike_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likeunlike',
        ),
    ]
