# Generated by Django 4.1.2 on 2022-10-24 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('likeunlike', '0002_alter_likeunlike_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeunlike',
            name='author',
        ),
        migrations.RemoveField(
            model_name='likeunlike',
            name='post',
        ),
        migrations.AddField(
            model_name='likeunlike',
            name='author',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likeunlike',
            name='post',
            field=models.ManyToManyField(related_name='likes', to='posts.post'),
        ),
    ]
