# Generated by Django 4.1.2 on 2022-10-24 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
        ('likeunlike', '0003_remove_likeunlike_author_remove_likeunlike_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeunlike',
            name='author',
        ),
        migrations.RemoveField(
            model_name='likeunlike',
            name='post',
        ),
        migrations.AddField(
            model_name='likeunlike',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likeunlike',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.post'),
        ),
    ]
